### ISSUE TITLE
"new game" button

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/minesweeper#13]
new game button needs to do:
- delete everything that is on canvas
- draw unopened squares everywhere
- change `current_game` to a new `Game` instance
- something else I forgot?

Edit: updated list to use `class Game` introduced in b8c99a07a5b852f870f9cd5402c7deee893d4077

**Comment by Akuli** [comment]
Some things with the code added in ffda92860853a42708365b2ea8f0232a29f928bc still need to be fixed:

- [x] Set `current_game` to a new `Game` object and get rid of `current_game.dict_or_list.clear()`
- [x] Call `new_game()` when the program starts (and a new game begins)
- [x] Get rid of copy/pasted `***Lets go!***` (it's enough to have it in `new_game()`)
- [x] Get rid of copy/pasted loop that draws unopened squares
- [ ] Delete all items on the canvas from the old game because they are no longer needed

**Comment by ThePhilgrim** [comment]
ARE YOU COMPLAINING ABOUT MY CODE, HUH?????!!!!!!
I MADE IT WORK, I AM PROUD, YOU GO TO BED WITHOUT DINNER!

**Comment by Akuli** [comment]
Setting `current_game` to a new Game object is done like this:

```
global current_game
current_game = Game()
```

`global` is bad style, but it's unavoidable in this situation. We can later clean  up the code to use another class to avoid it, but that's beyond the scope of this issue.

**Comment by ThePhilgrim** [comment]
> Setting `current_game` to a new Game object is done like this:
> 
> ```
> global current_game
> current_game = Game()
> ```
> 
> `global` is bad style, but it's unavoidable in this situation. We can later clean up the code to use another class to avoid it, but that's beyond the scope of this issue.

global current_game
current_game = Game()

This doesn't wipe anything on the canvas.. it just lets me click it again.

**Comment by Akuli** [comment]
It replaces `current_game.some_list_or_dict.clear()`, not any of the other code in `new_game()`.
