### ISSUE TITLE
u explode if u click on correctly flagged mine

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/minesweeper#15]

**Comment by ThePhilgrim** [comment]
I think you do in the original as well ? A flag doesn't prevent you from dying if you then click on the mine.

**Comment by Akuli** [comment]
In the past, I have programmed my minesweeper games to do nothing if you left-click on a flag. Feel free to close this issue if you don't want your minesweeper to work like that.

**Comment by ThePhilgrim** [comment]
Now you can't left-click flags.

**Comment by Akuli** [comment]
https://github.com/ThePhilgrim/minesweeper/blob/ffda92860853a42708365b2ea8f0232a29f928bc/minesweeper.py#L47-L50

This is the code that should prevent left-clicking flags, and it's currently commented out. Removing flags was added in 202f618

**Comment by Akuli** [comment]
This code should also use `self` instead of `current_game`. There are other occurrences of `current_game` in the same method, and those should be changed to `self` too.
