### ISSUE TITLE
Show how many mines are not flagged yet

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/minesweeper#19]
Let's say that there are 200 mines and 197 flags. I think there should be something that says "3 mines not flagged yet" or "197/200 mines flagged" or something like that.

**Comment by Arrinao** [comment]
I honestly think we should just add a counter for flags. Otherwise you could win the game by just placing the flags around and watching if the counter moves or not (which it should if you place the flag on the mine position). Maybe my understanding is wrong though

**Comment by Akuli** [comment]
Fixed in 00570c9
