### ISSUE TITLE
 buttons look weird because ThePhilgrim changed my beautiful button width

### ISSUE THREAD

**Issue by Arrinao** [ThePhilgrim/minesweeper#2]
And I'm really really MAD!!!!

**Comment by Akuli** [comment]
Let's all try different button widths and comment here what looks best. We can then write code to use my favorite width on Linux, @ThePhilgrim's favorite width on mac, and @Arrinao's favorite width on windows.

**Comment by Akuli** [comment]
2

**Comment by Arrinao** [comment]
It's 3!

**Comment by Akuli** [comment]
I'm closing this issue because we are going to display the buttons with an image file on a canvas. It will look consistent on different platforms.
