### ISSUE TITLE
Issue in return of user_clicked_square

### ISSUE THREAD

**Issue by ThePhilgrim** [ThePhilgrim/minesweeper#3]
At the moment the function returns None.

I'd like it to return adjacent_mines from function mines_around_square, but there is a scope problem.
I would like to keep ajacent_mines inside mines_around_square. Is there another way to solve this?

**Comment by Akuli** [comment]
Why should it return adjacent mines?

**Comment by Akuli** [comment]
Maybe I should clarify what I meant with the above comment. Instead of returning the number of adjacent mines, it can display it in the button, and it doesn't have to return anything. But we don't know yet how to display a number in the canvas, so that will have to wait.

**Comment by Akuli** [comment]
See #9 for current status of `user_clicked_square` function
