### ISSUE TITLE
Tiny code cleanups

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/minesweeper#30]
- [x] `open_squares`: combine `if coordinate in A` and `if coordinate in B` into `if coordinate in A or coordinate in B`
- [x] `open_squares`: move animated gif code to `else` to avoid an unnecessary `... and coordinate not in self.mine_locations` check
- [x] Move `doomguy.gif` loading code into the same place with all other image loading code so that it's easier to find
- [x] ~Replace `self.game_over == False` with `not self.game_over`~

**Comment by ThePhilgrim** [comment]
Ticked the first box in latest push of or #40.

Don't know how to fix the other 2

**Comment by Akuli** [comment]
Animated gif code will be moved to `else` in #46
