### ISSUE TITLE
canvas looks weird

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/minesweeper#4]
- Only half of top row of buttons is visible
- Only half of left column of buttons is visible
- There's a black `__|` shaped area on the right side of buttons

To fix this, the buttons should be moved right by half of the button size. It can be fixed in this code:

```
        canvas.create_image((x, y), image=button_image)
```

The default is to interpret `(x,y)` as the **center** coordinates of each button. But if we change it to means top-left instead of center, then the buttons will move right and down by half width. I think adding `anchor='nw'` should do that.

**Comment by Arrinao** [comment]
Fixed via adding anchor='nw'
