### ISSUE TITLE
Minesweeper installer needed

### ISSUE THREAD

**Issue by ThePhilgrim** [ThePhilgrim/minesweeper#6]
Remember to make the program installable, so Python doesn't need to be installed in order to run it.

**Comment by ThePhilgrim** [comment]
Akuli, I have made a functioning mac installer. I am not sure how it needs to be treated on github. Do I git add the folder it's in? Only the file? Anything else I need to think about?

**Comment by Akuli** [comment]
Same as for Arrinao: make a new pull request that adds instructions for creating it to README (i.e. what commands to run), but don't commit the resulting installer.

**Comment by Akuli** [comment]
finally done!
