### ISSUE TITLE
time weirdness

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/minesweeper#69]
Currently the timer works in a very weird way:
- `game_time` is an attribute of `Game`, but unlike other attributes, it's defined in `new_game()` instead of `Game.__init__`.
- Initially, `game_time` is set to midnight of 1st January 2021. Then it's incremented by one second in a callback that runs once per second. This has a couple problems:
    - If a game lasts 60 minutes, then the timer shows zero, because `game_time` is 1 AM, with minutes and seconds both being zero again. Therefore the best high scores can be achieved by playing the game for e.g. 60 minutes and one second.
    - For high score list purposes, it's impossible to calculate the actual duration of the game with more than one second of precision.
    - The code looks weird. Why midnight of 1st January 2021?

Yes, this code was written before we did pull requests and code reviews.

To fix this, I would rewrite the code to work like this instead:
- `game_time` is initially set in `__init__`, not `new_game()`
- `game_time` does not start from midnight of 1st January 2021, but instead `datetime.datetime.now()` which is the time of clicking new game button (and making a new `Game` object)
- Instead of incrementing `game_time`, just do `(datetime.datetime.now() - game_time).total_seconds()`, which calculates the time since starting the game. Unfortunately there's no way to do nice `strftime("%M:%S")` with subtracted datetimes (timedeltas), so that code would instead become something like `f"{int(seconds / 60)}:{seconds % 60}"`. But that would work even with 60 or more minutes.
- Maybe switch from `datetime.datetime.now()` to `time.time()` which directly returns seconds, since we only need seconds anyway?

**Comment by Arrinao** [comment]
I've set it to 01:01:0000 because at the time (and actually even now) I didn't know a better way to make the clock start from 00:00.
